"""
Django settings for WebsiteforGWStore project.

Generated by 'django-admin startproject' using Django 1.8.4.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = ')!pe8b9l4$1d8x-&9a#@h5-w==5lth7cuf=1#gg0k83s#+e5d3'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = (
    'gwstore',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

ROOT_URLCONF = 'WebsiteforGWStore.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,  'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'WebsiteforGWStore.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'gwstore',
        'USER': 'postgres',
        'PASSWORD': '1qazxsw2',
        'HOST': '127.0.0.1',
        'PORT': '5432',
    }
}

# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'US/Eastern'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = 'C:\\GWStoreStaticFiles'
"""TEMPLATE_DIRS = (
    os.path.join(BASE_DIR,  'templates'),
)"""

EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = 'fastontimecotevertu@gmail.com'
EMAIL_HOST_PASSWORD = '1qazxsw2'
EMAIL_PORT = 587
EMAIL_USE_TLS = True

LOGIN_URL="/login/"

# WKHTML2PDF configuration on Ubuntu
MY_BILLS_SAVING_PATH = u"/home/ubuntu/PDF_Bill_Sent_To_Clients/{0}"
MY_PATH_TO_WKHTMLTOPDF = r'/home/ubuntu/wkhtml2pdf/usr/local/bin/wkhtmltopdf'.encode("UTF-8")
MY_BARCODE_SAVING_PATH = u"/home/ubuntu/PDF_Barcode_Printed/{0}"
MY_BATCH_BILLS_SAVING_PATH_FOR_SUBMITTING_TO_FASTONTIME = u"/home/ubuntu/PDF_Bill_Sent_To_Fastontime/{0}"